#  SQLite version 3.x
#  gem install sqlite3

development:
  adapter: postgresql
  encoding: unicode
  database: aviary_development
  pool: 5


test:
  adapter: postgresql
  encoding: unicode
  database: aviary_test
  pool: 5


production:
  adapter: postgresql
  encoding: unicode
  database: aviary_production
  pool: 5
